author = ["William F Godoy <williamfgc@yahoo.com>"]

[compat]
julia = "1.6"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"

 
